# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', 'vendor']


# Site Settings
title: "byteMAL Conference 2019"
email: "byteMALevents@gmail.com"
description: "Bioinformatics for Young inTernational researchers Expo"
baseurl: ""
url: "https://bytemal.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: "bytemal.org"
siteVerification: ""

# Organizer Info
organizerName: "JRC Combine"
organizerAlternateName: "Joint Research Group for Computational Biomedicine"
organizerDescription: ""
organizerEmail: "byteMALevents@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.combine.rwth-aachen.de/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@JRC-COMBINE"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}

# Hero Block
heroImage: "dna.jpg"
heroTitle: "byteMAL <typeout> 2019"
eventDate: "24. September, 2019"
typeoutTextValues: '"", "Liege", "Maastricht", "Aachen"'
typeoutFallback: ""
heroButtons:
 #- {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#subscribe", text: "Register Here"}

# About Block
aboutTitle: "About byteMAL"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "ByteMAL (Bioinformatics for Young inTernational researchers) is a conference for young researchers in the fields of bioinformatics and computational biology. It aims to provide a new networking platform for knowledge and expertise exchange across borders." }
 - {title: "Presentations", image: "hackathon.jpg", text: "Join us for three talks of experts in the domain, presenting tomorrows state of the art!" }
 - {title: "Poster Session", image: "workshop.jpg", text: "Networking, close interaction and hours of discussion. Come and get to know the research community!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "100", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "6", specialCharacter: "+", info: "hours", detail: "of Bioinformatics"}
 - {count: "3", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "15", specialCharacter: "+", info: "posters", detail: "presenting current work"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Meet our Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Großer Seminarraum Uniklinikum Aachen"
venueFeatures: ["Pauwelsstraße 30, 52074 Aachen, Germany"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "byteMAL2019"
twitterFeed: "https://twitter.com/hashtag/byteMAL2019?src=hash"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Reserve your seat"
subscribeAction: ""
subscribeInfo: "Register Now! Registration will close 2019-09-17 !"

# Footer
socialLinks:
 - {link: "https://www.facebook.com/bytemal", icon: "facebook"}
 - {link: "https://twitter.com/byteMAL", icon: "twitter"}
footerBlocks:
 -
  title: "Contacts"
  links:
   - {link: "mailto:byteMALevents@gmail.com", text: "byteMALevents@gmail.com"}
 -
  title: "Previous Bytemals"
  links:
    - {link: "https://projects.bigcat.unimaas.nl/bytemal/preview-events/maastricht/", text: "Bytemal 2016"}
    - {link: "https://projects.bigcat.unimaas.nl/bytemal/2017-2/", text: "Bytemal 2017"}
    - {link: "/", text: "Bytemal 2018 (TBD)"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Team Block
teamBlockTitle: "About us"
aboutUs: >
  Back in 2016 PhD students from the fields of systems biomedicine and bioinformatics from the EUREGIO region decided to establish a collaborative platform among students from Aachen, Germany; Maastricht, Netherlands and Liège, Belgium called ByteMAL - Bioinformatics for Young inTernational researchers Expo in Maastricht, Aachen and Liège.
  <br />
  The platform is aimed to exchange knowledge and discuss research ideas and challenges with people of similar backgrounds. A series of byteMAL conferences was set up as the most suitable option to achieve this goal.
  <br />
  byteMAL is a conference series aimed especially at young researchers in the fields of bioinformatics, computational biology and systems biomedicine. Every year it takes place in one of the three locations – Aachen, Maastricht or Liège. This year it is going to take place in RWTH Aachen University Hospital, Aachen, Germany.  
  <br />
  Each conference is opened by three keynote presentations from experienced researchers with a goal to provide an overview of the latest advancements in their respective fields. Afterwards participants will get the chance to network by presenting their own current work through posters and pitch presentations.
  <br />
  We will be happy to have you on board for the ByteMAL 2019!

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false
