# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', 'vendor']


# Site Settings
title: "byteMAL Conference 2019"
email: "byteMALevents@gmail.com"
description: "Bioinformatics for Young inTernational researchers Expo"
baseurl: ""
url: "https://bytemal.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: "bytemal.org"
siteVerification: ""

# Organizer Info
organizerName: "JRC Combine"
organizerAlternateName: "Joint Research Group for Computational Biomedicine"
organizerDescription: ""
organizerEmail: "byteMALevents@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.combine.rwth-aachen.de/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@JRC-COMBINE"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Hero Block
heroImage: "dna.jpg"
heroTitle: "byteMAL <typeout> 2019"
eventDate: "24. September, 2019"
typeoutTextValues: '"", "Liege", "Maastricht", "Aachen"'
typeoutFallback: ""
heroButtons:
 #- {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#subscribe", text: "Register Here"}

# About Block
aboutTitle: "About byteMAL"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "ByteMAL (Bioinformatics for Young inTernational researchers) is a conference for young researchers in the fields of bioinformatics and computational biology. It aims to provide a new networking platform for knowledge and expertise exchange across borders." }
 - {title: "Presentations", image: "hackathon.jpg", text: "Join us for three talks of experts in the domain, presenting tomorrows state of the art!" }
 - {title: "Poster Session", image: "workshop.jpg", text: "Networking, close interaction and hours of discussion. Come and get to know the research community!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "100", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "6", specialCharacter: "+", info: "hours", detail: "of Bioinformatics"}
 - {count: "3", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "15", specialCharacter: "+", info: "posters", detail: "presenting current work"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Meet our Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Seminarraum Uniklinikum Aachen"
venueFeatures: ["Right in the heart of Aachen.", "Sufficient place for up to 100 people.", "Modern and attractive."]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "byteMAL2019"
twitterFeed: "https://twitter.com/hashtag/byteMAL2019?src=hash"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Reserve your seat"
subscribeAction: ""
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Footer
socialLinks:
 - {link: "https://www.facebook.com/bytemal", icon: "facebook"}
 - {link: "https://twitter.com/byteMAL", icon: "twitter"}
footerBlocks:
 -
  title: "Contacts"
  links:
   - {link: "mailto:byteMALevents@gmail.com", text: "byteMALevents@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Team Block
teamBlockTitle: "About us"
aboutUs: ""

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false
